import "../globals.css";

export const metadata = {
  title: 'ShareHub - Policy',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`inter.className bg-gray-900`}>
          <div>{children}</div>
      </body>
    </html>
  )
}
